### BUSCAR / TRAER todos los libros - GET - OK
GET  http://localhost:8080/books

### BUSCAR / TRAER un libro por ID - GET - OK
GET  http://localhost:8080/books/

### CREAR un libro - POST - OK
POST http://localhost:8080/books
Content-Type: application/json

{
    "title": "Ficciones",
    "description": "Colección de cuentos filosóficos y fantásticos",
    "authorId":"683f3465c8be75cc1a49dc16"
}

### ACTUALIZAR datos de Libros - PATCH - OK
PATCH http://localhost:8080/books/683f9398831a6949692f00ec
Content-Type: application/json

{
    "price": 150,
    "stock": 200
}

### ELIMINAR un Libro por ID - DELETE - OK
DELETE http://localhost:8080/books