### BUSCAR / TRAER todos los libros - GET - OK
GET  http://localhost:8080/books

### BUSCAR / TRAER un libro por ID - GET - OK
GET  http://localhost:8080/books/683f9398831a6949692f00ec

### BUSCAR / TRAER un libro por ID - GET - NULL
GET  http://localhost:8080/books/683f9398831a6949692f00ec

### CREAR un libro - POST - OK
POST http://localhost:8080/books
Content-Type: application/json

{
    "title": "Bestiario",
    "description": "Relatos cortos cargados de simbolismo",
    "authorId":"683f347ec8be75cc1a49dc18"
}

### ACTUALIZAR datos de Libros - PATCH - OK
PATCH http://localhost:8080/books/683f9398831a6949692f00ec
Content-Type: application/json

{
    "title":"",
    "price": 150,
    "stock": 200
}

### ELIMINAR un Libro por ID - DELETE - OK
DELETE http://localhost:8080/books/684075fa3ff3ada76bf03c09
